# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 526c5a7ca127ef5269bba823406a860b6008691085e15c6175f1dd3d77334954a251c660cc40e2833181a337dbccf768e3dae2023786fa31713e58a651007466

test:
  secret_key_base: f4018ae1bf9c1fc245eb54afc22fe8c34c5e8515977e68ee1050d8d00b0aa67c25e188959bcdafd07b8e8dd7c598495ea8b0e12eb510663a8da48e1cae3b7032

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
